### ISSUE TITLE
Stylistic rules on the config

### ISSUE THREAD

**Issue by Ne3l** [cpojer/eslint-config#2]
This configuration is meant to be used with Typescript and Prettier yet there are some stylistic rules on it:

- https://github.com/cpojer/eslint-config/blob/main/index.js#L47
- https://github.com/cpojer/eslint-config/blob/main/index.js#L89
- etc...

is there any reason for not using https://github.com/prettier/eslint-config-prettier or can i open a PR cleaning up it?

just had a conflict between prettier and the Eslint autofix.

` 6:27  error    Unexpected space before function parentheses  space-before-function-paren`

To reproduce: 

- Eslint: 8.56.0
- Prettier: 3.2.2

```ts
export function Wrapper<
  T extends Record<string, (...args: any[]) => unknown>,
>(service: T) {}
```

**Comment by cpojer** [comment]
Fixed in 1.14.0, see https://github.com/cpojer/eslint-config/commit/fefc139e1f7293970f554bb111bf7b3e7fd6030e.

This was mostly a leftover, and I was going to wait for ESLint 9 to remove them completely since they are deprecated. I did keep some like `curly` around since they come with an autofix.
